import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
IMG = HERE.parent / "img"
OUT = HERE / "loading.svg"

ORDER = ["frame_0_8", "frame_1", "frame_2", "frame_3",
         "frame_4", "frame_5", "frame_6", "frame_7"]

VIEWBOX = "64 105 79 130"
WIDTH, HEIGHT = 79, 130

FRAME_MS = 150
CYCLE_S = len(ORDER) * FRAME_MS / 1000
SWITCH_MS = CYCLE_S


def drawing_of(name):
    text = (IMG / f"{name}.svg").read_text(encoding="utf-8")

    defs = re.search(r"<defs\b.*?(?:/>|</defs>)", text, re.S)
    body = text[defs.end():].rsplit("</svg>", 1)[0]

    body = re.sub(r'\s+(?:inkscape|sodipodi):[\w-]+="[^"]*"', "", body)
    body = re.sub(r'\s+id="[^"]*"', "", body)
    body = re.sub(r"\n\s*\n", "\n", body)

    return "\n".join("      " + line.strip()
                     for line in body.splitlines() if line.strip())


delays = "\n".join(
    f"    .frame.f{i} {{ animation-delay: {i * FRAME_MS / 1000:.3f}s; }}"
    for i in range(len(ORDER))
)

frames = "\n".join(
    f'  <g class="frame f{i}">\n{drawing_of(name)}\n  </g>'
    for i, name in enumerate(ORDER)
)

OUT.write_text(f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
================================================================================
 BAKLAVA - loading animation
================================================================================
 DO NOT EDIT THIS FILE BY HAND. It is assembled from the eight drawings in
 static/img/frame_*.svg by static/anim/build_loading_animation.py - change a
 frame, run that script, and this file is rewritten.

 It is one ordinary picture, so it goes anywhere an image goes:
     <img src="/static/anim/loading.svg">
 The animation is inside the file (the style block below), which is why it
 needs no JavaScript and cannot fall out of step with the page.

 HOW IT WORKS
 The eight frames are eight groups, .f0 to .f{len(ORDER) - 1}, drawn on top of each
 other. They are invisible by default. The "flick" animation makes one of them
 visible for the first eighth of the cycle and hides it again for the rest;
 each frame starts {FRAME_MS}ms later than the one before it, so exactly one is on
 screen at any moment. After {CYCLE_S:g}s the whole thing repeats.

 TO CHANGE THE SPEED: put a longer (slower) or shorter (faster) time in
 FRAME_MS in the build script and run it again.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VIEWBOX}"
     width="{WIDTH}" height="{HEIGHT}" role="img" aria-label="Loading">
  <title>Loading</title>

  <style>
    .frame {{
      opacity: 0;
      animation: flick {CYCLE_S:g}s linear infinite;
    }}

    /* On for one eighth of the cycle, off for the other seven. The stops at
       12.4% and 12.5% are a switch, not a fade: they are {SWITCH_MS:g}ms apart,
       far too fast for an eye to catch. */
    @keyframes flick {{
      0%, 12.4%   {{ opacity: 1; }}
      12.5%, 100% {{ opacity: 0; }}
    }}

{delays}

    /* Someone who has asked their system for less motion gets the finished
       drawing, standing still, instead of the flicker. */
    @media (prefers-reduced-motion: reduce) {{
      .frame    {{ animation: none; }}
      .frame.f0 {{ opacity: 1; }}
    }}
  </style>

{frames}
</svg>
""", encoding="utf-8")

print(f"Wrote {OUT} - {len(ORDER)} frames, {CYCLE_S:g}s per cycle.")
