"""
================================================================================
 BAKLAVA - builds the loading animation
================================================================================
Run this after changing any of the drawings in static/img/frame_*.svg:

    python static/anim/build_loading_animation.py

It rewrites static/anim/loading.svg next to this file. Nothing else in the app
has to change - the page just picks up the new file.

WHAT IT DOES
Each frame_*.svg is a full A4 page from Inkscape whose drawing sits in a small
patch in the middle. For every frame this script takes the drawing out, throws
away the Inkscape bookkeeping (guides, layer names, ids), and stacks all eight
of them inside ONE svg, cropped down to the drawing itself. A small stylesheet
written into that svg then shows one frame at a time, which is what makes it
move without any JavaScript.

Only the standard library is needed - there is nothing to install.
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent          # static/anim/
IMG = HERE.parent / "img"                       # static/img/
OUT = HERE / "loading.svg"

# The cycle: the finished mark, rubbed out, drawn back in, and round again.
# frame_0_8 is both the first and the last frame, hence its name.
ORDER = ["frame_0_8", "frame_1", "frame_2", "frame_3",
         "frame_4", "frame_5", "frame_6", "frame_7"]

# The window onto the A4 page: "x y width height". The drawing occupies
# x 66.4..141.0 and y 107.4..233.3, so this is it with a little air around it.
# Redraw the mark somewhere else on the page and this needs adjusting - in
# Inkscape, Edit > Select All then read the X/Y/W/H boxes in the toolbar.
VIEWBOX = "64 105 79 130"
WIDTH, HEIGHT = 79, 130

FRAME_MS = 150                                  # how long one frame is on screen
CYCLE_S = len(ORDER) * FRAME_MS / 1000          # ...and one full round
SWITCH_MS = CYCLE_S                             # the 12.4% -> 12.5% gap, in ms


def drawing_of(name):
    """Returns the drawing of one frame: everything after <defs>, cleaned up."""
    text = (IMG / f"{name}.svg").read_text(encoding="utf-8")

    # Inkscape writes <defs> self-closing, so accept either ending.
    defs = re.search(r"<defs\b.*?(?:/>|</defs>)", text, re.S)
    body = text[defs.end():].rsplit("</svg>", 1)[0]

    # Inkscape-only attributes mean nothing to a browser, and the same id
    # repeated eight times in one file is invalid - both go.
    body = re.sub(r'\s+(?:inkscape|sodipodi):[\w-]+="[^"]*"', "", body)
    body = re.sub(r'\s+id="[^"]*"', "", body)
    body = re.sub(r"\n\s*\n", "\n", body)

    return "\n".join("      " + line.strip()
                     for line in body.splitlines() if line.strip())


# Every frame carries two class names: "frame" for what they all share, and
# "fN" for its turn in the queue. The delay rules are therefore written
# ".frame.fN" - as plain ".fN" the shared rule would outweigh them (it names an
# element as well as a class) and all eight frames would flash at once.
delays = "\n".join(
    f"    .frame.f{i} {{ animation-delay: {i * FRAME_MS / 1000:.3f}s; }}"
    for i in range(len(ORDER))
)

frames = "\n".join(
    f'  <g class="frame f{i}">\n{drawing_of(name)}\n  </g>'
    for i, name in enumerate(ORDER)
)

OUT.write_text(f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
================================================================================
 BAKLAVA - loading animation
================================================================================
 DO NOT EDIT THIS FILE BY HAND. It is assembled from the eight drawings in
 static/img/frame_*.svg by static/anim/build_loading_animation.py - change a
 frame, run that script, and this file is rewritten.

 It is one ordinary picture, so it goes anywhere an image goes:
     <img src="/static/anim/loading.svg">
 The animation is inside the file (the style block below), which is why it
 needs no JavaScript and cannot fall out of step with the page.

 HOW IT WORKS
 The eight frames are eight groups, .f0 to .f{len(ORDER) - 1}, drawn on top of each
 other. They are invisible by default. The "flick" animation makes one of them
 visible for the first eighth of the cycle and hides it again for the rest;
 each frame starts {FRAME_MS}ms later than the one before it, so exactly one is on
 screen at any moment. After {CYCLE_S:g}s the whole thing repeats.

 TO CHANGE THE SPEED: put a longer (slower) or shorter (faster) time in
 FRAME_MS in the build script and run it again.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VIEWBOX}"
     width="{WIDTH}" height="{HEIGHT}" role="img" aria-label="Loading">
  <title>Loading</title>

  <style>
    .frame {{
      opacity: 0;
      animation: flick {CYCLE_S:g}s linear infinite;
    }}

    /* On for one eighth of the cycle, off for the other seven. The stops at
       12.4% and 12.5% are a switch, not a fade: they are {SWITCH_MS:g}ms apart,
       far too fast for an eye to catch. */
    @keyframes flick {{
      0%, 12.4%   {{ opacity: 1; }}
      12.5%, 100% {{ opacity: 0; }}
    }}

{delays}

    /* Someone who has asked their system for less motion gets the finished
       drawing, standing still, instead of the flicker. */
    @media (prefers-reduced-motion: reduce) {{
      .frame    {{ animation: none; }}
      .frame.f0 {{ opacity: 1; }}
    }}
  </style>

{frames}
</svg>
""", encoding="utf-8")

print(f"Wrote {OUT} - {len(ORDER)} frames, {CYCLE_S:g}s per cycle.")
